CREATE TABLE [dbo].[InMemTable4] (
    [c1] INT        NOT NULL,
    [c2] NCHAR (48) NOT NULL,
    PRIMARY KEY NONCLUSTERED HASH ([c1]) WITH (BUCKET_COUNT = 1048576)
)
WITH (DURABILITY = SCHEMA_ONLY, MEMORY_OPTIMIZED = ON);

