CREATE TABLE [dbo].[WideTableNoNCIndexes] (
    [id]         BIGINT    IDENTITY (1, 1) NOT NULL,
    [createdate] DATETIME  NULL,
    [id2]        BIGINT    NULL,
    [id3]        BIGINT    NULL,
    [txtstr]     CHAR (10) NULL,
    [txtstr2]    CHAR (5)  NULL,
    [txtstr3]    CHAR (5)  NULL,
    [shipdate]   DATETIME  NULL,
    [flag]       BIT       NULL,
    [flag2]      BIT       NULL,
    [flag3]      BIT       NULL,
    [addr1]      CHAR (15) NULL,
    [addr2]      CHAR (15) NULL,
    [addr3]      CHAR (15) NULL,
    [pc]         CHAR (10) NULL,
    [txtstr4]    CHAR (10) NULL,
    [txtstr5]    CHAR (10) NULL,
    [id4]        BIGINT    NULL,
    [id5]        BIGINT    NULL,
    [moddate]    DATETIME  NULL,
    [archive]    BIT       NULL,
    [custid]     BIGINT    NULL,
    [id6]        BIGINT    NULL,
    [id7]        BIGINT    NULL,
    [txtstr6]    CHAR (7)  NULL,
    CONSTRAINT [PK_WideTableNoNCIndexes] PRIMARY KEY CLUSTERED ([id] ASC)
);

