INSERT INTO Guitar(GuitarName,OrderID,[Date]) VALUES('Gibson',11,GETDATE())
INSERT INTO Guitar(GuitarName,OrderID,[Date]) VALUES('Gibson',12,dateadd(YEAR,1, getdate()))
INSERT INTO Guitar(GuitarName,OrderID,[Date]) VALUES('Rickenbacker',13,dateadd(DAY,1, getdate()))
INSERT INTO Guitar(GuitarName,OrderID,[Date]) VALUES('Fender',1,dateadd(YEAR,2, getdate()))
INSERT INTO Guitar(GuitarName,OrderID,[Date]) VALUES('Gibson',21,dateadd(DAY,21, getdate()))
INSERT INTO Guitar(GuitarName,OrderID,[Date]) VALUES('Ibanez',41,dateadd(DAY,4, getdate()))
INSERT INTO Guitar(GuitarName,OrderID,[Date]) VALUES('Gibson',51,dateadd(YEAR,5, getdate()))
INSERT INTO Guitar(GuitarName,OrderID,[Date]) VALUES('FENDER',71,dateadd(DAY,7, getdate()))
INSERT INTO Guitar(GuitarName,OrderID,[Date]) VALUES('Gibson',81,dateadd(DAY,9, getdate()))
INSERT INTO Guitar(GuitarName,OrderID,[Date]) VALUES('Ibanez',91,dateadd(YEAR,2, getdate()))
